init_db:
	python3 -m scripts.init_db	

train_model:
	python3 -m scripts.train_model

test_db:
	python3 -m scripts.test_db

tensorflow:
	python3 -m scripts.tensorflow


run: init_db
	python -m api.main
