# Generated by Django 5.2.4 on 2025-08-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('isbn', models.CharField(max_length=13)),
                ('rating', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'ratings',
                'indexes': [models.Index(fields=['user_id'], name='ratings_user_id_bd9bb9_idx'), models.Index(fields=['isbn'], name='ratings_isbn_0bebba_idx')],
                'unique_together': {('user_id', 'isbn')},
            },
        ),
    ]
